#!/usr/bin/env python3
"""Validate a human-proposed input candidate and add generated output/provenance."""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import subprocess
from pathlib import Path


def exe_name(name: str) -> str:
    return name + (".exe" if os.name == "nt" else "")


def run(cmd: list[str], cwd: Path, inp: bytes, timeout: float) -> bytes:
    proc = subprocess.run(cmd, cwd=cwd, input=inp, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(f"command failed: {' '.join(cmd)}\n{proc.stderr.decode(errors='replace')}")
    return proc.stdout


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workdir", default=".")
    ap.add_argument("--input-file", required=True)
    ap.add_argument("--case-id", required=True)
    ap.add_argument("--tests-dir", default="tests")
    ap.add_argument("--provenance", default="provenance.json")
    ap.add_argument("--solution", default=None)
    ap.add_argument("--validator", default=None)
    ap.add_argument("--timeout", type=float, required=True)
    args = ap.parse_args()

    if args.timeout <= 0:
        raise SystemExit("--timeout must be positive")

    workdir = Path(args.workdir).resolve()
    input_data = Path(args.input_file).read_bytes()
    validator = args.validator or (str(workdir / exe_name("validator")) if (workdir / exe_name("validator")).exists() else None)
    if validator:
        run([validator], workdir, input_data, args.timeout)

    solution = args.solution or str(workdir / exe_name("solution"))
    output_data = run([solution], workdir, input_data, args.timeout)

    tests_dir = workdir / args.tests_dir
    tests_dir.mkdir(parents=True, exist_ok=True)
    in_path = tests_dir / f"{args.case_id}.in"
    out_path = tests_dir / f"{args.case_id}.out"
    in_path.write_bytes(input_data)
    out_path.write_bytes(output_data)

    prov_path = workdir / args.provenance
    if prov_path.exists():
        prov = json.loads(prov_path.read_text(encoding="utf-8"))
    else:
        prov = {"created_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(), "cases": []}
    if isinstance(prov, list):
        prov = {"cases": prov}
    prov.setdefault("cases", []).append(
        {
            "case_id": args.case_id,
            "source": "manual_candidate_validated",
            "generator_command": None,
            "generator_mode": "manual_candidate",
            "generator_args": [str(args.input_file)],
            "solution_command": [solution],
            "validator_command": [validator] if validator else None,
            "timeout_seconds": args.timeout,
            "input_file": str(in_path.relative_to(workdir)),
            "output_file": str(out_path.relative_to(workdir)),
            "input_sha256": sha256(input_data),
            "output_sha256": sha256(output_data),
            "created_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        }
    )
    prov_path.write_text(json.dumps(prov, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Adopted validated manual candidate as {args.case_id}; output generated by solution.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
